executors:
  node:
    docker:
      - image: circleci/node:10

version: 2

jobs:
  build:
    executor: node
    working_directory: ~/tmp

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

deploy:
  executor: node
  steps:
    - checkout
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

    - run: yarn install

    - run:
        name: Install netlify-cli
        command: sudo npm install -g --silent netlify-cli
    - run:
        name: Deploy to Netlify
        command: netlify deploy --dir=./public -p

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
